# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Pack and Promote

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore NuGet packages
        run: dotnet restore PackAndPromote.Tests/PackAndPromote.Tests.csproj

      - name: Build with dotnet
        run: dotnet build PackAndPromote/PackAndPromote.csproj --configuration Release

      - name: Run tests
        run: dotnet test PackAndPromote.Tests/PackAndPromote.Tests.csproj --configuration Release --no-restore --verbosity normal
        
      - name: dotnet publish
        run: dotnet publish PackAndPromote/PackAndPromote.csproj -c Release -o pack-and-promote-dev

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: pack-and-promote-dev

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pack-and-promote-dev'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.pack_and_promote_dev_8F28 }}
